# Generated by Django 4.1.4 on 2022-12-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('address', models.CharField(max_length=50, verbose_name='Direcccion')),
                ('image', models.ImageField(upload_to='Photo')),
                ('book', models.ManyToManyField(related_name='Libro', to='books.books')),
            ],
            options={
                'verbose_name': 'Library',
                'verbose_name_plural': 'Libraries',
                'db_table': 'Library',
            },
        ),
    ]
